export const PRISMA_CLIENT_NAME = Symbol('PRISMA_CLIENT_NAME');
export const PRISMA_MODULE_OPTIONS = Symbol('PRISMA_MODULE_OPTIONS');
export const PRISMA_CONNETIONS = Symbol('PRISMA_CONNECTIONS');
// export const PRISMA_DATABASE = Symbol('PRISMA_CONNECTION_NAME');
